### ISSUE TITLE
SegNet_PyTorch

### ISSUE THREAD

**Issue by nargesthy** [vinceecws/SegNet_PyTorch#1]
I try to run your **SegNet** script on **google Colab**. I had multiple issues I fixed, but I got stuck with the last one which is related to the **Train_SegNet.py** file. 
The error is as below:  

Resume training? (Y/N) Y
No checkpoint found at '/content/gdrive/MyDrive/Colab_Notebooks/seg_Narges/SegNet_PyTorch-master/checkpoint.pt'
Epoch 1:
^C

Your response is highly appreciated.

**Comment by vinceecws** [comment]
Hey, the script takes in absolute directories. Try passing in the full path.

**Comment by dyuming** [comment]
Can you share the camvid dataset you used?

**Comment by nargesthy** [comment]
> Hey, the script takes in absolute directories. Try passing in the full path.

Hi, Thank you for your response. Actually, the issue was solved after running the model on a local GPU, instead of Google Colab. The CamVid dataset is too large to be run on the colab.

**Comment by nargesthy** [comment]
> Can you share the camvid dataset you used?

Here is the link to download the CamVid dataset:
[http://mi.eng.cam.ac.uk/research/projects/VideoRec/CamVid/](url)

**Comment by vinceecws** [comment]
Good to hear, closing this issue!
