### ISSUE TITLE
No Training code in SegNet.py

### ISSUE THREAD

**Issue by kreuz1995** [vinceecws/SegNet_PyTorch#3]
There is no class method as Train in SegNet.py. But in Train_SegNet.py, it calls Train from SegNet.py

**Comment by vinceecws** [comment]
Hello, this must've been accidentally removed during refactoring. I've added the missing class and the training script should work now. Please pull the latest from master.

https://github.com/vinceecws/SegNet_PyTorch/blob/d870acccfeb6d99be38301981e1a5a14735d2d90/CamVid/SegNet.py#L166
